version: '3'

services:
    postgres:
        image: postgres:9.6.5
        container_name: conectadp2
        networks: 
            - network-do-papi 
        ports: 
            - "5432:5432"
        environment:
            POSTGRES_DB: 'postgres'
            POSTGRES_USER: 'postgres'
            POSTGRES_PASSWORD: 'postgres'

    python:
        build:
            dockerfile: ./Dockerfile
            context: .
        image: pythao_compose
        container_name: python
        ports: 
            - "5000:5000"
        networks: 
            - network-do-papi 
        depends_on: 
            - "postgres"
            
networks:
    network-do-papi:
        driver: bridge